import React, { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { createRoot } from "react-dom/client";
import "./dashboard.css";

type View = "overview" | "pipeline" | "clients" | "projects" | "tasks" | "finance" | "ai" | "marketing" | "systems" | "security";
type Profile = { userId: string; email: string; displayName: string; role: string; securityAdmin: boolean; aal: string | null };
type Row = Record<string, any>;
type Data = { profile: Profile; clients: Row[]; opportunities: Row[]; projects: Row[]; tasks: Row[]; invoices: Row[]; founderTransactions: Row[]; aiJobs: Row[]; settings: Record<string, any>; audit: Row[]; generatedAt: string };

const stageOrder = ["request", "qualification", "consulting", "customer_decision", "quote", "confirmed", "deposit_50", "planning", "hardware_concept", "software_development", "procurement", "installation", "installation_30", "configuration", "acceptance", "final_invoice_20", "completed", "maintenance"];
const stageLabels: Record<string, string> = {
  request: "Anfrage", qualification: "Qualifikation", consulting: "Beratung", customer_decision: "Kundenentscheid", quote: "Offerte", confirmed: "Auftrag", deposit_50: "Anzahlung 50 %", planning: "Planung", hardware_concept: "Hardware-Konzept", software_development: "Software", procurement: "Beschaffung", installation: "Montage", installation_30: "Montagezahlung 30 %", configuration: "Einrichtung", acceptance: "Abnahme", final_invoice_20: "Schlusszahlung 20 %", completed: "Erledigt", maintenance: "Betreuung", paused: "Pausiert", lost: "Verloren", cancelled: "Storniert",
};
const responsibility: Record<string, string> = { marcel: "Marcel", thomas: "Thomas", shared: "Gemeinsam", ai: "KI" };
const nav: Array<{ id: View; label: string; icon: string }> = [
  { id: "overview", label: "Übersicht", icon: "grid" }, { id: "pipeline", label: "Trichter", icon: "funnel" },
  { id: "clients", label: "Kunden", icon: "users" }, { id: "projects", label: "Projekte", icon: "briefcase" },
  { id: "tasks", label: "Aufgaben", icon: "check" }, { id: "finance", label: "Finanzen", icon: "finance" },
  { id: "ai", label: "KI-Bots", icon: "spark" }, { id: "marketing", label: "Marketing", icon: "megaphone" },
  { id: "systems", label: "Systeme", icon: "screen" }, { id: "security", label: "Sicherheit", icon: "shield" },
];

function Icon({ name, size = 20 }: { name: string; size?: number }) {
  const paths: Record<string, React.ReactNode> = {
    grid: <><rect x="3" y="3" width="7" height="7"/><rect x="14" y="3" width="7" height="7"/><rect x="3" y="14" width="7" height="7"/><rect x="14" y="14" width="7" height="7"/></>,
    funnel: <path d="M3 5h18l-7 8v6l-4 2v-8z"/>, users: <><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M22 21v-2a4 4 0 0 0-3-3.87M16 3.13a4 4 0 0 1 0 7.75"/></>,
    briefcase: <><rect x="3" y="7" width="18" height="13" rx="2"/><path d="M8 7V5a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2M3 12h18M10 12v2h4v-2"/></>, check: <><path d="M9 11l3 3L22 4"/><path d="M21 12v7a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h11"/></>,
    finance: <><rect x="2" y="5" width="20" height="14" rx="2"/><path d="M2 10h20M6 15h3"/></>, spark: <><path d="m12 3 1.2 4.2L17 9l-3.8 1.8L12 15l-1.2-4.2L7 9l3.8-1.8zM19 15l.7 2.3L22 18l-2.3.7L19 21l-.7-2.3L16 18l2.3-.7z"/></>,
    megaphone: <><path d="m3 11 16-7v16L3 13zM11 17l1 4H7l-1-6"/><path d="M19 9a3 3 0 0 1 0 6"/></>, screen: <><rect x="2" y="3" width="20" height="14" rx="2"/><path d="M8 21h8M12 17v4"/></>, shield: <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/>,
    plus: <path d="M12 5v14M5 12h14"/>, close: <path d="m6 6 12 12M18 6 6 18"/>, logout: <><path d="M10 17l5-5-5-5M15 12H3"/><path d="M14 3h5a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2h-5"/></>, arrow: <path d="M5 12h14M13 6l6 6-6 6"/>, menu: <path d="M4 6h16M4 12h16M4 18h16"/>, refresh: <><path d="M20 11a8 8 0 1 0-2.34 5.66"/><path d="M20 4v7h-7"/></>, lock: <><rect x="4" y="10" width="16" height="11" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3"/></>,
  };
  return <svg aria-hidden="true" width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">{paths[name] ?? paths.grid}</svg>;
}

async function api(path: string, options?: RequestInit) {
  const response = await fetch(`/api/dashboard/${path}`, { credentials: "same-origin", ...options, headers: { "Content-Type": "application/json", ...(options?.headers || {}) } });
  const body = await response.json().catch(() => ({}));
  if (!response.ok) throw Object.assign(new Error(body.error || "Anfrage fehlgeschlagen"), { status: response.status, code: body.code });
  return body;
}

const money = (value: unknown) => new Intl.NumberFormat("de-CH", { style: "currency", currency: "CHF" }).format(Number(value || 0));
const shortDate = (value: unknown) => value ? new Intl.DateTimeFormat("de-CH", { day: "2-digit", month: "2-digit", year: "numeric" }).format(new Date(String(value))) : "–";
const company = (row: Row) => Array.isArray(row.client) ? row.client[0]?.company_name : row.client?.company_name;

function Login({ onLoggedIn }: { onLoggedIn: () => void }) {
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setError(""); try { await api("login", { method: "POST", body: JSON.stringify({ email, password }) }); onLoggedIn(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  return <main className="auth-shell"><section className="auth-brand"><div className="brand"><span>Swiss</span><b>Compact</b></div><p>Operations Dashboard</p><h1>Alles im Blick.<br/>Vom Lead bis zur Wartung.</h1><p className="auth-copy">Der geschützte Arbeitsbereich für Projekte, Kunden, Finanzen und automatisierte Abläufe.</p></section><section className="auth-card"><div className="auth-lock"><Icon name="lock" size={24}/></div><p className="eyebrow">Sicherer Zugang</p><h2>Anmelden</h2><p className="muted">Nur für autorisierte SwissCompact-Administratoren.</p><form onSubmit={submit}><label>E-Mail<input type="email" autoComplete="username" value={email} onChange={e => setEmail(e.target.value)} required autoFocus/></label><label>Passwort<input type="password" autoComplete="current-password" value={password} onChange={e => setPassword(e.target.value)} required/></label>{error && <p className="form-error" role="alert">{error}</p>}<button className="primary full" disabled={busy}>{busy ? "Wird geprüft …" : "Sicher anmelden"}<Icon name="arrow"/></button></form><p className="auth-foot">Nach der Anmeldung ist ein Code aus der Authenticator-App erforderlich.</p></section></main>;
}

function Mfa({ state, onVerified }: { state: any; onVerified: () => void }) {
  const [enrollment, setEnrollment] = useState<any>(null); const [code, setCode] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  useEffect(() => { if (state.mfaEnrollmentRequired && !enrollment) api("mfa", { method: "POST", body: JSON.stringify({ action: "enroll" }) }).then(setEnrollment).catch(e => setError(e.message)); }, [state.mfaEnrollmentRequired, enrollment]);
  const factorId = enrollment?.factorId || state.factorId;
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setError(""); try { await api("mfa", { method: "POST", body: JSON.stringify({ action: "verify", factorId, code }) }); onVerified(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  return <main className="mfa-shell"><section className="mfa-card"><div className="auth-lock"><Icon name="shield" size={26}/></div><p className="eyebrow">Zwei-Faktor-Schutz</p><h1>{state.mfaEnrollmentRequired ? "Authenticator verbinden" : "Identität bestätigen"}</h1>{state.mfaEnrollmentRequired ? <><p>Scanne den QR-Code mit deiner Authenticator-App. Bewahre den Schlüssel sicher auf.</p>{enrollment?.qrCode ? <img className="qr" src={enrollment.qrCode} alt="QR-Code für Authenticator"/> : <div className="qr-loading">QR-Code wird erstellt …</div>}{enrollment?.secret && <code className="secret">{enrollment.secret}</code>}</> : <p>Gib den sechsstelligen Code aus deiner Authenticator-App ein.</p>}<form onSubmit={submit}><label>Sicherheitscode<input className="code-input" inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" maxLength={6} value={code} onChange={e => setCode(e.target.value.replace(/\D/g, ""))} required autoFocus/></label>{error && <p className="form-error">{error}</p>}<button className="primary full" disabled={busy || !factorId || code.length !== 6}>{busy ? "Wird bestätigt …" : "Code bestätigen"}</button></form></section></main>;
}

function Stat({ label, value, note, tone }: { label: string; value: string | number; note: string; tone?: string }) { return <article className={`stat ${tone || ""}`}><span>{label}</span><strong>{value}</strong><small>{note}</small></article>; }
function Empty({ children = "Noch keine Einträge." }: { children?: React.ReactNode }) { return <div className="empty">{children}</div>; }

function Overview({ data, go }: { data: Data; go: (v: View) => void }) {
  const openInvoices = data.invoices.filter(i => !["paid", "cancelled"].includes(i.status)); const pipeline = data.opportunities.filter(o => !["completed", "lost", "cancelled"].includes(o.stage)); const pipelineValue = pipeline.reduce((s, o) => s + Number(o.value_chf || 0), 0);
  return <><header className="page-head"><div><p className="eyebrow">Operations Cockpit</p><h1>Guten Tag, {data.profile.displayName.split(" ")[0]}.</h1><p>Hier läuft heute alles zusammen.</p></div><button className="primary" onClick={() => go("pipeline")}><Icon name="plus"/>Neue Anfrage</button></header><section className="stats"><Stat label="Aktive Chancen" value={pipeline.length} note={`${money(pipelineValue)} im Trichter`}/><Stat label="Offene Projekte" value={data.projects.filter(p => p.status !== "completed").length} note="Planung, Umsetzung und Betrieb"/><Stat label="Offene Aufgaben" value={data.tasks.length} note={`${data.tasks.filter(t => t.priority === "urgent").length} dringend`}/><Stat label="Offene Rechnungen" value={money(openInvoices.reduce((s, i) => s + Number(i.amount || 0), 0))} note="Zahlungsziel 14 Tage" tone="red"/></section><div className="overview-grid"><section className="panel span-2"><PanelHead title="Aktueller Auftragstrichter" action="Öffnen" onClick={() => go("pipeline")}/><div className="stage-strip">{stageOrder.slice(0, 7).map(stage => <div key={stage}><strong>{data.opportunities.filter(o => o.stage === stage).length}</strong><span>{stageLabels[stage]}</span></div>)}</div><div className="recent-list">{pipeline.slice(0, 5).map(o => <div className="recent-row" key={o.id}><div><b>{o.title}</b><span>{company(o) || "Noch ohne Kundenkartei"}</span></div><span className="tag">{stageLabels[o.stage]}</span><strong>{money(o.value_chf)}</strong></div>)}{!pipeline.length && <Empty>Lege die erste Kundenanfrage an.</Empty>}</div></section><section className="panel"><PanelHead title="Nächste Aufgaben" action="Alle" onClick={() => go("tasks")}/><div className="task-list">{data.tasks.slice(0, 5).map(t => <div className="task-mini" key={t.id}><span className={`priority ${t.priority}`}/><div><b>{t.title}</b><small>{responsibility[t.responsibility]} · {shortDate(t.due_at)}</small></div></div>)}{!data.tasks.length && <Empty/>}</div></section><section className="panel"><PanelHead title="Zahlungsplan" action="Finanzen" onClick={() => go("finance")}/><div className="payment-plan"><div><b>50 %</b><span>vor Projektstart</span></div><div><b>30 %</b><span>bei Montagebeginn</span></div><div><b>20 %</b><span>nach Kundenabnahme</span></div></div><p className="panel-note">Software-Abos sind vom Projektzahlungsplan ausgenommen.</p></section><section className="panel span-2"><PanelHead title="Aktivitätsprotokoll" action="Sicherheit" onClick={() => go("security")}/><div className="audit-grid">{data.audit.slice(0, 6).map(a => <div key={a.id}><span>{a.actor_email}</span><b>{a.action} · {a.entity_type}</b><small>{shortDate(a.created_at)}</small></div>)}{!data.audit.length && <Empty/>}</div></section></div></>;
}

function PanelHead({ title, action, onClick }: { title: string; action?: string; onClick?: () => void }) { return <div className="panel-head"><h2>{title}</h2>{action && <button className="text-button" onClick={onClick}>{action}<Icon name="arrow" size={16}/></button>}</div>; }

function Pipeline({ data, mutate, openModal }: { data: Data; mutate: Function; openModal: Function }) {
  const activeStages = stageOrder.filter(stage => data.opportunities.some(o => o.stage === stage) || stageOrder.indexOf(stage) < 6);
  return <><header className="page-head"><div><p className="eyebrow">Vertrieb & Umsetzung</p><h1>Auftragstrichter</h1><p>Vom Erstkontakt bis zur langfristigen Betreuung.</p></div><button className="primary" onClick={() => openModal("opportunity")}><Icon name="plus"/>Anfrage erfassen</button></header><div className="pipeline-scroll"><div className="pipeline-board">{activeStages.map((stage, index) => <section className="pipeline-column" key={stage}><header><span>{String(index + 1).padStart(2, "0")}</span><h2>{stageLabels[stage]}</h2><b>{data.opportunities.filter(o => o.stage === stage).length}</b></header><div>{data.opportunities.filter(o => o.stage === stage).map(o => <article className="deal" key={o.id}><small>{company(o) || "Ohne Kunde"}</small><h3>{o.title}</h3><strong>{money(o.value_chf)}</strong><div className="deal-foot"><span>{responsibility[o.owner_area]}</span><select aria-label="Phase ändern" value={o.stage} onChange={e => mutate({ action: "move_opportunity", id: o.id, stage: e.target.value })}>{stageOrder.map(s => <option value={s} key={s}>{stageLabels[s]}</option>)}</select></div></article>)}{!data.opportunities.some(o => o.stage === stage) && <div className="column-empty">Keine Vorgänge</div>}</div></section>)}</div></div></>;
}

function Clients({ data, openModal }: { data: Data; openModal: Function }) { return <><header className="page-head"><div><p className="eyebrow">CRM</p><h1>Kundenkartei</h1><p>Kontakte, Beziehungen und laufende Chancen zentral geführt.</p></div><button className="primary" onClick={() => openModal("client")}><Icon name="plus"/>Kunde erfassen</button></header><section className="panel table-panel"><table><thead><tr><th>Kundennummer</th><th>Unternehmen</th><th>Kontakt</th><th>E-Mail</th><th>Status</th></tr></thead><tbody>{data.clients.map(c => <tr key={c.id}><td><code>{c.customer_number}</code></td><td><strong>{c.company_name}</strong></td><td>{c.contact_name || "–"}</td><td>{c.email || "–"}</td><td><span className="tag">{c.lifecycle}</span></td></tr>)}</tbody></table>{!data.clients.length && <Empty>Noch keine Kunden. Neue Anfrage oder Kunde erfassen.</Empty>}</section></> }

function Projects({ data }: { data: Data }) { return <><header className="page-head"><div><p className="eyebrow">Delivery</p><h1>Projekte</h1><p>Planung, Hardware, Software, Montage und Abnahme.</p></div></header><div className="card-grid">{data.projects.map(p => <article className="project-card" key={p.id}><div className="project-top"><code>{p.order_number}</code><span className="tag">{stageLabels[p.status] || p.status}</span></div><h2>{p.title}</h2><p>{company(p) || "Kunde nicht zugeordnet"}</p><div className="pay-progress"><PaymentStep label="50 %" done={p.deposit_received}/><PaymentStep label="30 %" done={p.installation_payment_received}/><PaymentStep label="20 %" done={p.final_payment_received}/></div><small>Zieltermin: {shortDate(p.target_completion)}</small></article>)}{!data.projects.length && <Empty>Projekte entstehen nach bestätigtem Auftrag.</Empty>}</div></> }
function PaymentStep({ label, done }: { label: string; done: boolean }) { return <div className={done ? "done" : ""}><span>{done && <Icon name="check" size={10}/>}</span><b>{label}</b></div>; }

function Tasks({ data, mutate, openModal }: { data: Data; mutate: Function; openModal: Function }) { return <><header className="page-head"><div><p className="eyebrow">Gemeinsame Planung</p><h1>Aufgaben</h1><p>Getrennte Verantwortlichkeiten, eine gemeinsame Übersicht.</p></div><button className="primary" onClick={() => openModal("task")}><Icon name="plus"/>Aufgabe</button></header><section className="panel"><div className="task-table">{data.tasks.map(t => <article key={t.id}><button className="task-check" aria-label="Aufgabe erledigen" onClick={() => mutate({ action: "complete_task", id: t.id })}/><div><h3>{t.title}</h3><p>{t.description}</p></div><span className={`tag ${t.priority}`}>{t.priority}</span><b>{responsibility[t.responsibility]}</b><time>{shortDate(t.due_at)}</time></article>)}{!data.tasks.length && <Empty>Alles erledigt.</Empty>}</div></section></> }

function Finance({ data, mutate }: { data: Data; mutate: Function }) {
  const marcel = data.founderTransactions.filter(t => t.paid_by === "marcel").reduce((s, t) => s + Number(t.amount_chf), 0); const thomas = data.founderTransactions.filter(t => t.paid_by === "thomas").reduce((s, t) => s + Number(t.amount_chf), 0); const companyExpenses = data.founderTransactions.filter(t => t.transaction_type === "company_expense").reduce((s, t) => s + Number(t.amount_chf), 0);
  return <><header className="page-head"><div><p className="eyebrow">Interne Buchhaltung</p><h1>Finanzen</h1><p>Doppelte Buchhaltung, Belege und monatlicher 50/50-Ausgleich.</p></div><button className="secondary" disabled><Icon name="plus"/>Buchung erfassen</button></header><section className="notice"><Icon name="finance"/><div><b>Vorgründungsphase</b><span>SwissCompact Kollektivgesellschaft ist für 2027 geplant. Bis dahin werden Vorgänge Marcel Spahr als Rechnungssteller zugeordnet.</span></div></section><section className="stats"><Stat label="Marcel ausgelegt" value={money(marcel)} note="Gesellschafterdarlehen"/><Stat label="Thomas ausgeglichen" value={money(thomas)} note="Überweisung an Marcel"/><Stat label="Wirtschaftliche Belastung" value={money(companyExpenses / 2)} note="Ziel pro Inhaber"/><Stat label="MWST-Monitor" value={money(0)} note="Warnung ab CHF 80’000"/></section><section className="panel table-panel"><PanelHead title="Gründerbewegungen"/><table><thead><tr><th>Datum</th><th>Beschreibung</th><th>Bezahlt von</th><th>Kategorie</th><th>Beleg</th><th>Betrag</th></tr></thead><tbody>{data.founderTransactions.map(t => <tr key={t.id}><td>{shortDate(t.transaction_date)}</td><td><strong>{t.description}</strong></td><td>{responsibility[t.paid_by]}</td><td><input className="inline-input" defaultValue={t.category || ""} placeholder="Kategorie" onBlur={e => { if (e.target.value !== (t.category || "")) mutate({ action: "update_founder_transaction", id: t.id, category: e.target.value }); }}/></td><td><span className={`tag ${t.receipt_path ? "success" : "warning"}`}>{t.receipt_path ? "Vorhanden" : "Ausstehend"}</span></td><td><b>{money(t.amount_chf)}</b></td></tr>)}</tbody></table></section><section className="finance-grid"><div className="panel"><PanelHead title="Zahlungslogik Projekte"/><div className="large-pay"><div><strong>50 %</strong><span>Anzahlung vor Start</span></div><div><strong>30 %</strong><span>bei Montagebeginn</span></div><div><strong>20 %</strong><span>nach Abnahme</span></div></div></div><div className="panel"><PanelHead title="Kontrolle"/><ul className="check-list"><li>Vier-Augen-Freigabe für Zahlungen</li><li>Korrekturbuchungen statt Löschen</li><li>CSV und CAMT.053 vorbereitet</li><li>Monatsausgleich erst nach Bestätigung</li></ul></div></section></>;
}

const bots = [
  ["Lead-Bot", "Qualifiziert Anfragen und bereitet Kundendossiers vor."], ["Beratungs-Bot", "Erstellt Briefings, Fragen und Gesprächszusammenfassungen."], ["Offerten-Bot", "Bereitet Kalkulationen und Offerten zur Freigabe vor."], ["Projekt-Bot", "Plant Meilensteine, Aufgaben, Risiken und Übergaben."], ["Finanz-Bot", "Prüft Belege, Kontierung und Liquiditätswirkung."], ["Mahn-Bot", "Überwacht Fälligkeiten und entwirft Erinnerungen."], ["Bindungs-Bot", "Erkennt Wartungs-, Ausbau- und Abo-Potenziale."], ["Marketing-Bot", "Plant Inhalte und publiziert nach freigegebenem Monatsplan."],
];
function AiBots({ data }: { data: Data }) { const spent = data.aiJobs.reduce((s, j) => s + Number(j.actual_cost_chf || 0), 0); return <><header className="page-head"><div><p className="eyebrow">Automatisierung</p><h1>KI-Bots</h1><p>Administrative Arbeit automatisieren – mit klaren Freigabegrenzen.</p></div></header><section className="budget"><div><span>Monatsbudget</span><strong>{money(spent)} <small>von CHF 100</small></strong></div><div className="budget-track"><i style={{ width: `${Math.min(100, spent)}%` }}/><span style={{ left: "70%" }}>Warnung 70</span></div></section><div className="bot-grid">{bots.map(([name, desc], index) => <article key={name}><div className="bot-icon"><Icon name="spark"/></div><span className="tag">{index < 2 ? "bereit" : "vorbereitet"}</span><h2>{name}</h2><p>{desc}</p><small>Externe oder bindende Aktionen benötigen Freigabe.</small></article>)}</div></> }

function Marketing() { return <Generic title="Marketing" eyebrow="Wachstum" intro="Website, Newsletter, LinkedIn, Instagram, Facebook und Google Ads in einem genehmigten Monatsplan."><div className="channel-grid">{["Website", "Newsletter", "LinkedIn", "Instagram & Facebook", "Google Ads"].map(x => <article key={x}><Icon name="megaphone"/><h3>{x}</h3><span className="tag warning">Integration ausstehend</span></article>)}</div><section className="notice"><Icon name="shield"/><div><b>Publikationsregel</b><span>Der Marketing-Bot darf innerhalb eines von beiden Admins freigegebenen Monatsplans selbstständig publizieren. Neue Kampagnen und Budgets benötigen erneut beide Freigaben.</span></div></section></Generic> }
function Systems() { return <Generic title="Systeme & Displaysteuerung" eyebrow="Technik" intro="Geräte, Inhalte, Standorte und Software-Abonnements werden als getrenntes Modul aufgebaut."><div className="card-grid"><InfoCard title="Display-Flotte" text="Heartbeat, Gerätestatus, Fernwartung und Offline-Cache."/><InfoCard title="Inhaltssteuerung" text="Playlists, Zeitpläne, Freigaben und sichere Auslieferung."/><InfoCard title="Software-Abos" text="Essential, Business und Enterprise – kombiniert pro Standort und Display."/></div><section className="notice"><Icon name="screen"/><div><b>Getrenntes Kundenportal</b><span>Kunden erhalten unter /portal ausschliesslich Zugriff auf ihre eigenen Projekte, Dokumente und später ihre Displaysteuerung.</span></div></section></Generic> }
function Security({ data }: { data: Data }) { return <Generic title="Sicherheit & Protokoll" eyebrow="Administration" intro="Zwei-Faktor-Schutz, unveränderbare Nachvollziehbarkeit und getrennte Sicherheitsrechte."><section className="security-grid"><InfoCard title="Zwei-Faktor-Authentifizierung" text={`Aktiv für ${data.profile.displayName} · Sicherheitsstufe ${data.profile.aal || "AAL1"}`}/><InfoCard title="Rolle" text={data.profile.securityAdmin ? "Hauptadmin: Benutzer, Backups und Integrationen verwalten." : "Admin: volle operative Lese- und Schreibrechte."}/><InfoCard title="Backups" text="Tägliche Datenbanksicherung, Dokumentexport und getesteter Wiederherstellungsplan vorgesehen."/></section><section className="panel table-panel"><PanelHead title="Letzte Änderungen"/><table><thead><tr><th>Zeitpunkt</th><th>Benutzer</th><th>Aktion</th><th>Objekt</th></tr></thead><tbody>{data.audit.map(a => <tr key={a.id}><td>{shortDate(a.created_at)}</td><td>{a.actor_email}</td><td>{a.action}</td><td>{a.entity_type}</td></tr>)}</tbody></table>{!data.audit.length && <Empty/>}</section></Generic> }
function Generic({ title, eyebrow, intro, children }: { title: string; eyebrow: string; intro: string; children: React.ReactNode }) { return <><header className="page-head"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{intro}</p></div></header>{children}</> }
function InfoCard({ title, text }: { title: string; text: string }) { return <article className="info-card"><div className="info-mark"/><h2>{title}</h2><p>{text}</p></article>; }

function Modal({ type, clients, close, submit }: { type: string; clients: Row[]; close: () => void; submit: (x: any) => void }) {
  const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  async function handle(e: FormEvent<HTMLFormElement>) { e.preventDefault(); setBusy(true); setError(""); const f = new FormData(e.currentTarget); const values = Object.fromEntries(f.entries()); try { await submit({ action: `create_${type}`, ...values }); close(); } catch (err) { setError((err as Error).message); } finally { setBusy(false); } }
  const title = type === "client" ? "Kunde erfassen" : type === "task" ? "Aufgabe erstellen" : "Anfrage erfassen";
  return <div className="modal-backdrop" onMouseDown={e => { if (e.target === e.currentTarget) close(); }}><section className="modal" role="dialog" aria-modal="true"><header><div><p className="eyebrow">Neuer Eintrag</p><h2>{title}</h2></div><button className="icon-button" onClick={close} aria-label="Schliessen"><Icon name="close"/></button></header><form onSubmit={handle}>{type === "client" && <><label>Unternehmen<input name="companyName" required autoFocus/></label><div className="form-row"><label>Kontaktperson<input name="contactName"/></label><label>Telefon<input name="phone"/></label></div><label>E-Mail<input type="email" name="email"/></label></>}{type === "opportunity" && <><label>Bezeichnung<input name="title" required autoFocus placeholder="z. B. Displays Showroom Bern"/></label><label>Kunde<select name="clientId"><option value="">Noch nicht zugeordnet</option>{clients.map(c => <option value={c.id} key={c.id}>{c.company_name}</option>)}</select></label><div className="form-row"><label>Potenzial CHF<input name="valueChf" type="number" min="0" step="100"/></label><label>Verantwortung<select name="ownerArea"><option value="shared">Gemeinsam</option><option value="marcel">Marcel</option><option value="thomas">Thomas</option><option value="ai">KI</option></select></label></div><label>Nächste Aktion<textarea name="nextAction" rows={3}/></label></>}{type === "task" && <><label>Aufgabe<input name="title" required autoFocus/></label><label>Beschreibung<textarea name="description" rows={3}/></label><div className="form-row"><label>Verantwortung<select name="responsibility"><option value="shared">Gemeinsam</option><option value="marcel">Marcel</option><option value="thomas">Thomas</option><option value="ai">KI</option></select></label><label>Priorität<select name="priority"><option value="normal">Normal</option><option value="high">Hoch</option><option value="urgent">Dringend</option><option value="low">Tief</option></select></label></div><label>Fällig am<input name="dueAt" type="datetime-local"/></label></>}{error && <p className="form-error">{error}</p>}<footer><button type="button" className="secondary" onClick={close}>Abbrechen</button><button className="primary" disabled={busy}>{busy ? "Speichert …" : "Speichern"}</button></footer></form></section></div>;
}

function Dashboard({ initial, logout }: { initial: Data; logout: () => void }) {
  const [data, setData] = useState(initial); const [view, setView] = useState<View>("overview"); const [modal, setModal] = useState<string | null>(null); const [menu, setMenu] = useState(false); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState("");
  const refresh = useCallback(async () => setData(await api("overview")), []);
  async function mutate(payload: any) { setBusy(true); setNotice(""); try { await api("records", { method: "POST", body: JSON.stringify(payload) }); await refresh(); setNotice("Änderung gespeichert"); } catch (e) { setNotice((e as Error).message); throw e; } finally { setBusy(false); } }
  const content = useMemo(() => ({ overview: <Overview data={data} go={setView}/>, pipeline: <Pipeline data={data} mutate={mutate} openModal={setModal}/>, clients: <Clients data={data} openModal={setModal}/>, projects: <Projects data={data}/>, tasks: <Tasks data={data} mutate={mutate} openModal={setModal}/>, finance: <Finance data={data} mutate={mutate}/>, ai: <AiBots data={data}/>, marketing: <Marketing/>, systems: <Systems/>, security: <Security data={data}/> })[view], [data, view]);
  return <div className="dashboard-shell"><aside className={menu ? "open" : ""}><div className="sidebar-head"><div className="brand"><span>Swiss</span><b>Compact</b></div><button className="icon-button mobile-only" onClick={() => setMenu(false)}><Icon name="close"/></button></div><p className="workspace-label">Operations</p><nav>{nav.map(item => <button key={item.id} className={view === item.id ? "active" : ""} onClick={() => { setView(item.id); setMenu(false); }}><Icon name={item.icon}/><span>{item.label}</span>{item.id === "tasks" && data.tasks.length > 0 && <b>{data.tasks.length}</b>}</button>)}</nav><div className="sidebar-foot"><div className="avatar">{data.profile.displayName.split(" ").map(x => x[0]).join("")}</div><div><b>{data.profile.displayName}</b><span>{data.profile.securityAdmin ? "Hauptadmin" : "Admin"}</span></div><button className="icon-button" onClick={logout} aria-label="Abmelden"><Icon name="logout"/></button></div></aside>{menu && <button className="sidebar-shade" aria-label="Navigation schliessen" onClick={() => setMenu(false)}/>}<main className="dashboard-main"><div className="mobile-bar"><button className="icon-button" onClick={() => setMenu(true)}><Icon name="menu"/></button><div className="brand"><span>Swiss</span><b>Compact</b></div><button className="icon-button" onClick={() => refresh()}><Icon name="refresh"/></button></div>{busy && <div className="top-progress"/>}<div className="page">{content}</div></main>{notice && <button className="toast" onClick={() => setNotice("")}>{notice}</button>}{modal && <Modal type={modal} clients={data.clients} close={() => setModal(null)} submit={mutate}/>}</div>;
}

function App() {
  const [state, setState] = useState<any>({ loading: true });
  const boot = useCallback(async () => { setState({ loading: true }); try { const session = await api("session"); if (session.mfaRequired || session.mfaEnrollmentRequired) setState({ loading: false, session }); else setState({ loading: false, data: await api("overview") }); } catch { setState({ loading: false }); } }, []);
  useEffect(() => { boot(); }, [boot]);
  if (state.loading) return <div className="boot"><div className="brand"><span>Swiss</span><b>Compact</b></div><i/></div>;
  if (state.session) return <Mfa state={state.session} onVerified={boot}/>;
  if (!state.data) return <Login onLoggedIn={boot}/>;
  return <Dashboard initial={state.data} logout={async () => { await api("logout", { method: "POST", body: "{}" }).catch(() => {}); setState({ loading: false }); }}/>;
}

createRoot(document.getElementById("dashboard-root")!).render(<React.StrictMode><App/></React.StrictMode>);
